// Code generated by tools/pgmsg. DO NOT EDIT.
//
// Source: src/bin/pg_dump/po/{de,fr}.po at REL_13_STABLE .. REL_18_STABLE
// (github.com/postgres/postgres). Regenerate with `just gen-messages`.

package parser

// messages is what pg_restore prints, mapped to what it means. Ordered
// longest-literal-first, so the first match is the most specific one.
var messages = []message{
	// "connecting to database for restore" (13-18)
	{literal: "connecting to database for restore", exact: true, kind: KindInfo, shape: shapeNone},
	// "entering main parallel loop" (13-18)
	{literal: "entering main parallel loop", exact: true, kind: KindInfo, shape: shapeNone},
	// "finished main parallel loop" (13-18)
	{literal: "finished main parallel loop", exact: true, kind: KindInfo, shape: shapeNone},
	// "processing data for table \"%s.%s\"" (13-18)
	{literal: "processing data for table ", exact: false, kind: KindProcessingData, shape: shapeQuotedName},
	// "while PROCESSING TOC:" (13-18)
	{literal: "while PROCESSING TOC:", exact: true, kind: KindInfo, shape: shapeNone},
	// "while INITIALIZING:" (13-18)
	{literal: "while INITIALIZING:", exact: true, kind: KindInfo, shape: shapeNone},
	// "while FINALIZING:" (13-18)
	{literal: "while FINALIZING:", exact: true, kind: KindInfo, shape: shapeNone},
	// "processing item %d %s %s" (13-18)
	{literal: "processing item ", exact: false, kind: KindProcessingItem, shape: shapeItem},
	// "from TOC entry %d; %u %u %s %s %s" (13-18)
	{literal: "from TOC entry ", exact: false, kind: KindUnknown, shape: shapeTOCEntry},
	// "launching item %d %s %s" (13-18)
	{literal: "launching item ", exact: false, kind: KindLaunchItem, shape: shapeItem},
	// "finished item %d %s %s" (13-18)
	{literal: "finished item ", exact: false, kind: KindFinishItem, shape: shapeItem},
	// "executing %s %s" (13-18), "executing %s" (13-18)
	{literal: "executing ", exact: false, kind: KindExecuting, shape: shapeDescName},
	// "creating %s \"%s.%s\"" (13-18), "creating %s \"%s\"" (13-18)
	{literal: "creating ", exact: false, kind: KindCreating, shape: shapeDescQuoted},
	// "dropping %s %s" (13-18)
	{literal: "dropping ", exact: false, kind: KindDropping, shape: shapeDescTag},
}
